PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCM_TITLE4_IDS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCM_TITLE4_IDS-AIDID .
    FIELD ZCM_TITLE4_IDS-BEGDA .
    FIELD ZCM_TITLE4_IDS-ENDDA .
    FIELD ZCM_TITLE4_IDS-PLUS .
    FIELD ZCM_TITLE4_IDS-STATE_AID .
    FIELD ZCM_TITLE4_IDS-TUITION_ONLY .
    FIELD ZCM_TITLE4_IDS-TUIT_FEES_ONLY .
    FIELD ZCM_TITLE4_IDS-SEQUENCE .
    FIELD ZCM_TITLE4_IDS-CLRCURRTERM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCM_TITLE4_IDS-AIDID .
    FIELD ZCM_TITLE4_IDS-BEGDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
